services:
  gdal:
    build:
      context: .
      dockerfile: Dockerfile
    image: wherewild-gdal
    working_dir: /workspace
    user: "${DOCKER_UID}:${DOCKER_GID}"
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
      - "9101:9101"
    environment:
      - RCLONE_CONFIG=/workspace/docker/rclone.conf
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    mem_limit: 16g
    init: true
    stdin_open: true
    tty: true
