name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    environment: production
    steps:
      - name: Deploy API
        run: |
          cd ~/wherewild/backend-v2
          git pull origin main
          docker compose -f docker-compose.optiplex.yml build api
          docker compose -f docker-compose.optiplex.yml rm -sf api
          docker compose -f docker-compose.optiplex.yml up -d api
          docker builder prune -f --keep-storage 2gb
